### ISSUE TITLE
Should Implement Django 1.9 Migrations

### ISSUE THREAD

**Issue by zenware** [pinax/django-waitinglist#15]
`python manage.py syncdb` is deprecated.
Current Solution is to run `python manage.py migrate --run-syncdb`

This should be apparent in the documentation page, and I think it may as well be updated.
I would be happy to do this as I don't think it will take much time.

**Comment by paltman** [comment]
Thanks!

**Comment by zenware** [comment]
@paltman Should I update the project requirements from Django 1.4 as well, or is that something we want to remain backwards compatible with? I'm fairly new to the project.

**Comment by paltman** [comment]
Yes please. 1.8+ only. 

You can reference the Travis/tox/setup.py in https://github.com/pinax/pinax-starter-app

**Comment by zenware** [comment]
Hopefully, that pull request can close this issue, and I can create another which will include the actual newer migrations and testing updates, I figured a quick documentation change that helps get the project working with newer versions of Django should be on it's own, separate from a change that actually updates the software to specifically support the newer versions of Django
